In [38]:
import numpy as np 

### Basics

In [39]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [40]:
b = np.array([[2.0, 9.0, 3.5], [6.0, 4.5, 5.0]])
print(b)

[[2.  9.  3.5]
 [6.  4.5 5. ]]


In [41]:
#Get Dimension
a.ndim
# b.ndim

1

In [42]:
# Get Shape
b.shape

(2, 3)

In [43]:
# Get type
a.dtype

dtype('int32')

In [44]:
# Get Size
a.itemsize

4

In [45]:
#Get total size
a.size

3

Accessing/Changing specific elements, rows, columns, etc.

In [46]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print (c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [47]:
c.shape

(2, 7)

In [48]:
# Get a specific element [r, c]:
c[0, -6]

2

In [49]:
# Get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
# get a specific column
c[: , 6]

array([ 7, 14])

In [51]:
# Getting a little more fancy [startindex:endindex:stepsize]
c[0, 1:6:2]

array([2, 4, 6])

In [52]:
# Replacing one element to other
c[1, 6] = 34
print (c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 34]]


In [53]:
c[:, 2] = [1,2]
print(c)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 34]]


3-D EXAMPLES

In [54]:
d = np.array([[[1, 2],[3, 4]], [[5, 6], [7, 8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [55]:
# Get a specific element (work outside in)
d[:, 0, :]

array([[1, 2],
       [5, 6]])

In [56]:
# Replace
d[1, 1, 1] = 9
print (d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 9]]]


### Initializing Different Types of Arrays

In [57]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
#All 1s matrix
np.ones((4,2), dtype = 'int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [59]:
#Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [60]:
#Any other number (full_like)
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [61]:
#Random decimal number
np.random.rand(4, 2)

array([[0.54903726, 0.32697334],
       [0.25559358, 0.79679037],
       [0.6343672 , 0.34909789],
       [0.62104265, 0.47419727]])

In [62]:
np.random.random_sample(c.shape)

array([[0.85989669, 0.70482162, 0.22900751, 0.06705098, 0.01691085,
        0.81025841, 0.03046225],
       [0.68406409, 0.28557881, 0.24061545, 0.71572328, 0.62164869,
        0.69993531, 0.16134103]])

In [63]:
#Random Integer Values
np.random.randint(-4, 8, size=(3,3))

array([[-3, -2,  4],
       [ 4, -1,  6],
       [-3,  4,  7]])

In [64]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [66]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:
a = np.array([1, 2, 3])
b = a
b

array([1, 2, 3])

### Mathematics

In [68]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [69]:
a + 2

array([3, 4, 5, 6, 7])

In [70]:
a - 2

array([-1,  0,  1,  2,  3])

In [71]:
a * 2

array([ 2,  4,  6,  8, 10])

In [72]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [73]:
b = np.array([1, 0, 1, 0, 1])
print(b)

[1 0 1 0 1]


In [74]:
a + b

array([2, 2, 4, 4, 6])

In [75]:
a ** b

array([1, 1, 3, 1, 5])

In [76]:
a - b

array([0, 2, 2, 4, 4])

In [77]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

### Linear Algebra

In [79]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [80]:
# Find the determinanat
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [81]:
stats = np.array([[1, 2, 3],[4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np.min(stats, axis=1)

array([1, 4])

In [89]:
np.max(stats, axis=1)

array([3, 6])

In [93]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [95]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4+])