In [1]:
import numpy as np

In [2]:
x = [[1,2,3], [4,5,6], [7,1,0]]
ar = np.array(x)
print(ar)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [5]:
print(ar.sum(axis = 0))

[12  8  9]


In [6]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [7]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [8]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [9]:
ar.ndim

2

In [10]:
one = np.array([1,3,4,634,2])

In [11]:
one.argmax()

3

In [12]:
one.argmin()

0

In [16]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [18]:
ar.argmax()

6

In [19]:
ar.argmin()

8

In [20]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [21]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [22]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [23]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [24]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [25]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [26]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [30]:
ar.max()

7

In [31]:
ar.min()

0

In [32]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [34]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [33]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))